version: "3.9"
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
    - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
  consul:
    image: consul:latest
    hostname: localhost
    ports:
      - 8500:8500
  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - 9042:9042
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    #    volumes:
    #      - ./out/cassandra_data:/var/lib/cassandra
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
  cassandra-web:
    image: ipushc/cassandra-web
    ports:
      - 8083:9001
    environment:
      - "CASSANDRA_HOST=cassandra"

#  cassandra-load-keyspace:
#    container_name: cassandra-load-keyspace
#    image: cassandra:3.11.2
#    depends_on:
#      cassandra:
#        condition: service_healthy
#    volumes:
#      - ./src/main/resources/cassandra_schema.cql:/schema.cql
#    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"